# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e81016daddcfd4fe6ca91555e026da889bf988c0310ad4b2d08c590de142792267a1ba67ee1998403246eb37b688d31ef50bb9b675bede528b550eabd49e32c9

test:
  secret_key_base: 61809fd5381ef4c2aa172c3c01da7d3ec1ff103d96e634c6900d49455fd1e7ee4945812e6ed1cef00ccc549583864d011b758c3f43236949df4e887a21635890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
